# Generated by Django 4.0.2 on 2022-05-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('phonenumber', models.CharField(blank=True, max_length=45)),
                ('personal', models.CharField(blank=True, max_length=45)),
            ],
            options={
                'db_table': 'signup',
            },
        ),
    ]
